### ISSUE TITLE
[FLOSS] shellcheck

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4497]
Our scripts/Jenkins do not seem to run https://www.shellcheck.net/.

- [x] triage: check which shell scripts have no warning/errors with shellcheck
- [ ] create PR with auto-fixes
- [ ] [FLOSS H3] fix broken shell scripts
- [ ] [FLOSS H3] add a script similar to tests/shell/check_bashisms.sh
- [ ] [FLOSS T1] make sure one Docker container has shellcheck installed
- [ ] [FLOSS T1] Integrate shellcheck in Jenkins

**Comment by 0x6178656c** [comment]
I created a small helper script for this

```sh
#!/bin/bash

if [ -z ${1+x} ]; then
  echo "No severity level specified."
  exit 1
fi

SEVERITY="${1}"

for shell_script in $(find . -name '*.sh'); do
  shellcheck \
    --format=quiet \
    --severity="${SEVERITY}" \
    "${shell_script}"
  if [ $? -ne 0 ]; then
    echo "${shell_script}"
  fi
done
```

There seem to be quite a few issues:

```shell
root@5be86f640303:/libelektra# bash shellchecker.sh error | wc -l
38
root@5be86f640303:/libelektra# bash shellchecker.sh warning | wc -l
58
```

(This just lists the number of files affected and not the actual count of errors/warnings!)

The list of files with errors is:
```text
./src/tools/fuse/docker/create_keys_and_mount.sh
./tests/shell/check_spelling.sh
./tests/shell/check_export.sh
./tests/shell/check_distribution.sh
./tests/shell/check_spec.sh
./tests/shell/check_posix.sh
./tests/shell/run_all.sh
./tests/shell/check_merge.sh
./tests/shell/check_cmd_line_arguments.sh
./tests/shell/check_import.sh
./tests/shell/check_oclint.sh
./tests/shell/check_error.sh
./tests/shell/check_bashisms.sh
./tests/shell/generate_data.sh
./tests/shell/check_mount.sh
./tests/shell/check_basic.sh
./tests/shell/check_real_world.sh
./tests/shell/check_gen.sh
./tests/shell/check_resolver.sh
./tests/shell/check_meta.sh
./tests/shell/check_plugins.sh
./tests/shell/shell_recorder/shell_recorder.sh
./tests/shell/check_kdb_internal_check.sh
./tests/shell/check_doc.sh
./tests/shell/check_race.sh
./tests/shell/check_get_set.sh
./tests/shell/check_spec_set.sh
./tests/shell/check_kdb_internal_suite.sh
./tests/shell/check_formatting.sh
./tests/shell/external/pythongen.sh
./tests/shell/external/example_codegen_econf.sh
./tests/shell/external/example_codegen_tree.sh
./tests/shell/external/example_codegen_menu.sh
./tests/shell/external/mount_java.sh
./tests/shell/external/example.sh
./tests/shell/external/example_highlevel.sh
./scripts/vagrant/freebsd/provision.sh
./scripts/packaging/fedora/map_licenses.sh
```

Note that I have assumed that all shell scripts have the file extension `.sh` which of course needs not be the case. I will have a look if I can find shell scripts without the `.sh` extension.

**Comment by kodebach** [comment]
> Note that I have assumed that all shell scripts have the file extension .sh which of course needs not be the case. I will have a look if I can find shell scripts without the .sh extension

We already have `scripts/dev/reformat-shell`. Just take a look at what that does and try to cover the same files.

**Comment by markus2330** [comment]
> The list of files with errors is:

Thank you for investigating! Can you also check how many of the problems could be auto-fixed? (Use `-f diff` and pipe to `git apply`)

> Note that I have assumed that all shell scripts have the file extension .sh which of course needs not be the case. I will have a look if I can find shell scripts without the .sh extension.

`grep -rH '#!/bin/sh' * | grep -v sh:` should give you most.

`scripts/dev/reformat-shell` also does not cover all, I created #4559.

**Comment by kodebach** [comment]
Probably `#!/bin/[a-z]*sh` would be a better regex to also cover things like bash and zsh

**Comment by 0x6178656c** [comment]
I think you need to be even more defensive, e.g. `^#!\(/bin/\|/usr/bin/env \)[a-z]*sh$` or similar to also catch `/usr/bin/env` shebangs.

Of course, alternatively one could also enforce a standard, where only one type of shell is supported and scripts must start with a unique shebang.

**Comment by 0x6178656c** [comment]
Indeed, the [coding style guide](https://github.com/ElektraInitiative/libelektra/blob/master/doc/CODING.md#shell-guidelines) states that

> Please only use [POSIX](https://en.wikipedia.org/wiki/POSIX) functionality.

So probably it would be easiest to stick to `sh`. But I guess ultimately this is another issue (if any).

**Comment by markus2330** [comment]
There are also some scripts with /usr/bin e.g. scripts/completion/kdb-zsh-noglob

Yes, only POSIX is preferred. But there are some cases where other shells must be used, e.g. this shell completion of zsh cannot be written in POSIX.

> But I guess ultimately this is another issue (if any).

Hardcoding e.g. /usr/bin/zsh is also a bug, as it might be in /bin in some distributions. So /usr/bin/env is preferred for this. nixos had (or still has) only /usr/bin/env and /bin/sh as only executables without PATH.

Such problems can also be in the resulting bug report of what cannot be automatically fixed by shellcheck.

**Comment by 0x6178656c** [comment]
@markus2330  wrote:
> Can you also check how many of the problems could be auto-fixed? (Use `-f diff` and pipe to `git apply`)

I just ran this on the list I have provided above and for all of them `shellcheck` has the output

```
Issues were detected, but none were auto-fixable. Use another format to see them.
```

This means that no error can be auto-fixed.

**Comment by markus2330** [comment]
Cannot reproduce, e.g.:

```
shellcheck scripts/packaging/fedora/map_licenses.sh -f diff | git apply
```

produces:

```diff
--- a/scripts/packaging/fedora/map_licenses.sh
+++ b/scripts/packaging/fedora/map_licenses.sh
@@ -5,7 +5,7 @@
 
 LICENSE_FILE=$1
 
-LICENSES_WITHOUT_BSD=$(cat $LICENSE_FILE | grep "License:" | awk -F": " {' print $2'} | grep -v "^BSD.*" | sort | uniq | tr '\n' ',' | sed '$s/,$/\n/' | sed 's/,/ and /g')
+LICENSES_WITHOUT_BSD=$(cat "$LICENSE_FILE" | grep "License:" | awk -F": " {' print $2'} | grep -v "^BSD.*" | sort | uniq | tr '\n' ',' | sed '$s/,$/\n/' | sed 's/,/ and /g')
 
 declare -A arr
 
@@ -16,7 +16,7 @@
 arr["public-domain"]="Public Domain"
 
 for key in ${!arr[@]}; do
-       LICENSES_WITHOUT_BSD=$(echo $LICENSES_WITHOUT_BSD | sed "s/$key[^ ]*/${arr[${key}]}/g")
+       LICENSES_WITHOUT_BSD=$(echo "$LICENSES_WITHOUT_BSD" | sed "s/$key[^ ]*/${arr[${key}]}/g")
 done
 
 echo "BSD and $LICENSES_WITHOUT_BSD"

```

 which shellcheck version are you using?

**Comment by 0x6178656c** [comment]
Sorry, I should have been more precise. I only checked for errors (using the `--severity=error` flag).

The example you have provided is a style fix, I think. However, your remark made me double check and it does seem that some warnings are auto-fixable too. (My findings concerning errors remains true.)

These files provide a diff for warnings which can be applied without conflicts:

```
tests/shell/check_spelling.sh
tests/shell/check_posix.sh
tests/shell/run_all.sh
tests/shell/check_bashisms.sh
tests/shell/check_resolver.sh
tests/shell/check_formatting.sh
tests/shell/external/pythongen.sh
tests/shell/external/example_codegen_econf.sh
tests/shell/external/example_codegen_tree.sh
tests/shell/external/example_codegen_menu.sh
tests/shell/external/example.sh
tests/shell/external/example_highlevel.sh
```

For definitesness, I ran:
```sh
shellcheck --format=diff --severity=warning "$filename" | git apply
```

**Comment by markus2330** [comment]
Great work. I updated the top post that triage is done. Next steps (also above) are:

- PR with auto-fixes
- issue(s) with errors to fix: we should check what is important to fix and what could be fixed by simply changing shebang to bash

**Comment by 0x6178656c** [comment]
I played around with shellcheck some more and have found an auto-fix which is problematic (severity level info)

```diff
--- a/check_kdb_internal_check.sh
+++ b/check_kdb_internal_check.sh

-	"$KDB" plugin-check $ARGS "$PLUGIN" 1> "$FILE" 2> "$FILE"
+	"$KDB" plugin-check "$ARGS" "$PLUGIN" 1> "$FILE" 2> "$FILE"
```

The original file relies on shell expansion to pass `$ARGS` as multiple arguments, whereas with shellcheck's suggestion, this becomes a single argument `"$ARGS"`.

Since there are ~550 auto-fixes suggested when using the severity level info, checking all of the changes would be a lengthy task.

**Comment by kodebach** [comment]
I think most shell scripts are tests, so there would probably be a test failure, if something like in your example happens. If you create a PR, we could also divide review of the changed files among a few people if necessary.

**Comment by markus2330** [comment]
@0x6178656c what is open in this issue?

**Comment by 0x6178656c** [comment]
@markus2330 The step "[FLOSS H3] fix broken shell scripts" is essentially still open.
The test running in CI currently skips the files listed in [/tests/shell/check_shellcheck_ignorelist.txt](https://github.com/ElektraInitiative/libelektra/blob/b97c346c59c4f04af36002ef61cfa17ce8e759b4/tests/shell/check_shellcheck_ignorelist.txt).
The other points have all been done.

**Comment by markus2330** [comment]
Thank you, I created #4823 as follow-up. This can be closed now.
