### ISSUE TITLE
Proposal: Use Plugin Name in First Header of ReadMe 

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#482]
Currently most ReadMe documents (in the reference manual (PDF)) start with the section “ReadMe”. While this provides a little bit information about the content of the following text, most of the time it is not helpful at all. For example, the table of contents of the reference manual looks like this on my computer:

![toc](https://cloud.githubusercontent.com/assets/691989/12946157/a9076fcc-cff2-11e5-8679-f8539339c4f5.png)

I think it would be very helpful if the first header in every ReadMe reflects its content. For example, currently the ReadMe of the Augeas plugin looks like this:

``` Markdown
- infos = Information about augeas plugin is in keys below
...
- infos/description = reading and writing configurations via libaugeas

## INTRODUCTION ##
```

Something like this might be more helpful:

``` Markdown
- infos = Information about augeas plugin is in keys below
...
- infos/description = reading and writing configurations via libaugeas

# Augeas Plugin – Read and Write Configuration With Help from Augeas

## INTRODUCTION ##
```

**Comment by markus2330** [comment]
Yes, the situation is a bug/leftover. The pdf generation is a rather new feature, and not everything is adopted to it yet. @KurtMi Is it also possible to set the title by the folder name the file is in? That would be ok for all plugins.

For other files, we need a first level section, as you proposed. PRs are very welcomed!

**Comment by KurtMi** [comment]
I thought about that, it is in the queue.

**Comment by markus2330** [comment]
Can you fix it for this release? It also affects the html pages and makes the index if README.md pages quite useless.

**Comment by KurtMi** [comment]
Ok, when is the release date?

In the markdownlinkconverter README.md is a point from you under further improvements, namely:
* if title contains --, this should be @brief

what do yo mean by `@brief' ?

**Comment by markus2330** [comment]
The release date is 10 days ago (see github milestone 0.8.15), the actual release will be done when no release critical bugs are present. Blocking issues are also shown here: https://github.com/ElektraInitiative/libelektra/milestones/0.8.15  Hopefully today all implementation issues will be resolved and tomorrow is the release. So I think you still have time.

`@brief` is for [doxygen](https://www.stack.nl/~dimitri/doxygen/manual/docblocks.html) and is shown in indexes and summaries, because its only one line.

**Comment by KurtMi** [comment]
Ok, I am not sure if it is possible to set `@brief` in a Markdown file.

**Comment by KurtMi** [comment]
Made the title stuff #492.

> For other files, we need a first level section, as you proposed

What is meant with that?

**Comment by markus2330** [comment]
By first level section I mean the first (highest) level of markdown titles, e.g. `# first level section header #`

**Comment by markus2330** [comment]
Thank you, should be fixed now.

**Comment by sanssecours** [comment]
Looks like we reintroduced this problem. The index of the current PDF version of the manual looks almost the same as the one from my first screenshot:

<img width="182" alt="reference manual - index" src="https://cloud.githubusercontent.com/assets/691989/21245639/0da645dc-c324-11e6-8ac0-0c44da56c5c9.png">
.

**Comment by markus2330** [comment]
Thank you for reopening!

I updated the milestone!

**Comment by markus2330** [comment]
I have the same issue here. Doxygen 1.8.8

Furthermore external-links.txt is gone?

I tried to revert 889baa2ff9a0d5e1c7ad1a43e8d538e80ed8417d  without success: still only says README and no external-links.txt.

But 1ecd8e2b1a274ab61ad1f608c7f8ec575c26262d seems to cause the README problem, I reverted it.

But external-links.txt seems to be still gone?

**Comment by sanssecours** [comment]
> But 1ecd8e2 seems to cause the README problem, I reverted it.

😢 — As far as I can tell reverting 1ecd8e2 does not solve the problem on my machine. However, this change reintroduces the old problem of an „unstable” build: If we enable the option `BUILD_PDF`, then the build system will regenerate the PDF manual, even if we did not change a single source file.

**Comment by markus2330** [comment]
We can revert it back again. Can you bisect when the README and external-links work for you?

Hint: Better do a full rebuild in a full automated script (grep for correct title in html, see if external-links.txt is there), there are many commits since 11 Feb (when this issue was initially closed). Maybe you can add this script to scripts, so that others see how bisect can be automated.

**Comment by sanssecours** [comment]
> We can revert it back again.

That would be much appreciated. Did reverting the commit really fix the problem on your end? Did you try to regenerate the PDF documentation?

> Can you bisect when the README and external-links work for you?

I tried and found that, if I checkout e3ed8df9, then the documentation build does not work. This can be **incorrectly** 😳 fixed by applying commit 5f628938. After that the PDF table of contents does not include the names of the plugins.

This lead me to the conclusion, that I need to try e3ed8df9 in a **path that does not contain whitespace**. If I build the documentation there, then the index includes the name of the plugins. 

After this discovery I looked into the [change in Doxygen](https://github.com/doxygen/doxygen/pull/449/files) that broke the PDF build (on my machine) in the first place. Long story short, it looks like the proper fix is to replace 

```ini
FILTER_PATTERNS        = "*.md"="@MARKDOWN_LINK_CONVERTER@"
```

in `doc/Doxyfile` with

```ini
FILTER_PATTERNS        = *.md="\"@MARKDOWN_LINK_CONVERTER@\""
```
. However, I assume this fix only works if someone uses the newest version of Doxygen (`1.8.12`). I tried Doxygen 1.8.3.1, which does not produce a correct PDF manual.

**Comment by markus2330** [comment]
Really properly and nicely done, thanks a lot! Now titles, external-links.txt and building pdf all work perfectly.

I reopen the ticket for two documentation issues (see below).

> That would be much appreciated. Did reverting the commit really fix the problem on your end? Did you try to regenerate the PDF documentation?

Yes, it fixed the names, no I did not test PDF generation and it did not fix the external-links.txt.

> I tried Doxygen 1.8.3.1, which does not produce a correct PDF manual.

Maybe we should print a cmake warning in this case? Or at least mention the recommended doxygen version in COMPILE.md. With 1.8.8 the build works (1190 pages, 235 chapters)

Can you write a short script or paragraph (in doc/GIT.md) about bisect?
If you do not know what do I write, I can do it quickly.

**Comment by sanssecours** [comment]
>> I tried Doxygen 1.8.3.1, which does not produce a correct PDF manual.

> Maybe we should print a cmake warning in this case?

Printing a warning make sense, although I assume that most people use a version of Doxygen that should work (1.8.8+). Even [Debian Jessie (stable)](https://packages.debian.org/jessie/doxygen) packages a Doxygen version that meets this requirement. This makes me think that your second proposal to fix the issue:

> Or at least mention the recommended doxygen version in COMPILE.md.

should work well enough.

> Can you write a short script or paragraph (in doc/GIT.md) about bisect? If you do not know what do I write, I can do it quickly.

I only used `git bisect` once – when I was reading “[Pro Git](https://git-scm.com/book)”. I think you are much more qualified to write something about it.
